### ISSUE TITLE
Save error on existing document

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-client#17]
Click "Action.Edit" for a document in the dashboard and try to save it --  throws an error in the backend

```
IN: updateAknField
TypeError: Cannot read property 'value' of undefined
    at updateAknField (D:\develop\github\gawati\gawati-client-server\documentmanage.js:152:23)
    at Layer.handle [as handle_request] (D:\develop\github\gawati\gawati-client-server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\develop\github\gawati\gawati-client-server\node_modules\express\lib\router\route.js:137:13)
    at receiveSubmitData (D:\develop\github\gawati\gawati-client-server\documentmanage.js:32:5)
    at Layer.handle [as handle_request] (D:\develop\github\gawati\gawati-client-server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\develop\github\gawati\gawati-client-server\node_modules\express\lib\router\route.js:137:13)
    at jsonParser (D:\develop\github\gawati\gawati-client-server\node_modules\body-parser\lib\types\json.js:100:7)
    at Layer.handle [as handle_request] (D:\develop\github\gawati\gawati-client-server\node_modules\express\lib\router\layer.js:95:5)    at next (D:\develop\github\gawati\gawati-client-server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\develop\github\gawati\gawati-client-server\node_modules\express\lib\router\route.js:112:3)    at Layer.handle [as handle_request] (D:\develop\github\gawati\gawati-client-server\node_modules\express\lib\router\layer.js:95:5)
    at D:\develop\github\gawati\gawati-client-server\node_modules\express\lib\router\index.js:281:22    at Function.process_params (D:\develop\github\gawati\gawati-client-server\node_modules\express\lib\router\index.js:335:12)
    at next (D:\develop\github\gawati\gawati-client-server\node_modules\express\lib\router\index.js:275:10)    at Function.handle (D:\develop\github\gawati\gawati-client-server\node_modules\express\lib\router\index.js:174:3)
    at router (D:\develop\github\gawati\gawati-client-server\node_modules\express\lib\router\index.js:47:12)
```

**Comment by kohsah** [comment]
This has been fixed
